[tool.black]
line-length=79
skip-string-normalization=1
extend-exclude='''
(
    \.git
  | \.mypy_cache
  | \.venv
  | migrations
)
'''
[tool.isort] 
default_section = "THIRDPARTY" 
known_django = "django"
known_local_folder = ["brainforces", "quiz", "core", "users", "homepage", "archive", "organization"]
sections = ["FUTURE","STDLIB","THIRDPARTY","DJANGO","FIRSTPARTY","LOCALFOLDER"] 
skip = [".gitignore", "venv", "env"] 
skip_glob = ["*/migrations/*"] 
multi_line_output = 3
line_length = 79
lines_after_imports = 2